import { useState } from "react";
import { studentApi, userApi } from "../../api/services";
import { useLookups } from "../../lib/lookups";
import { pretty } from "../../lib/format";
import { useToast } from "../../lib/toast";
import { Badge, Button, Empty, ErrorBox, Field, Form, Loading, Modal, Search, Table, useAsync } from "../../ui/kit";
import type { Role } from "../../lib/types";

export function StudentsPage() {
  const { classes, sections, className } = useLookups();
  const [classId, setClassId] = useState("");
  const [q, setQ] = useState("");
  const list = useAsync(() => studentApi.list(classId || undefined), [classId]);
  const [open, setOpen] = useState(false);
  const toast = useToast();
  const [form, setForm] = useState({
    firstName: "", lastName: "", classId: "", sectionId: "", parentFirstName: "", parentLastName: "", relationship: "FATHER",
  });
  const rows = (list.data?.content || []).filter((s) => {
    const n = `${s.user?.fullName || ""} ${s.admissionNumber || ""}`.toLowerCase();
    return !q || n.includes(q.toLowerCase());
  });
  return (
    <>
      <div className="page-title">
        <div><h1>Students</h1><p>Enrolment writes a user + student row on Neon</p></div>
        <Button kind="brass" onClick={() => setOpen(true)}>Enrol student</Button>
      </div>
      <div className="row" style={{ marginBottom: 12 }}>
        <Search value={q} onChange={setQ} placeholder="Search name or admission no." />
        <select className="search" value={classId} onChange={(e) => setClassId(e.target.value)}>
          <option value="">All classes</option>
          {classes.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
        </select>
      </div>
      {list.loading ? <Loading /> : list.error ? <ErrorBox error={list.error} /> : (
        <Table
          headers={["Admission", "Name", "Class", "Roll", "Status"]}
          rows={rows.map((s) => [s.admissionNumber, s.user?.fullName || "—", className(s.classId), s.rollNumber || "—", <Badge key={s.id} value={s.status} />])}
        />
      )}
      <Modal title="Enrol student" open={open} onClose={() => setOpen(false)}>
        <Form
          onSubmit={async () => {
            try {
              const res = await studentApi.enroll(form);
              toast("ok", res.message || "Enrolled");
              if (res.studentAccount?.temporaryPassword) toast("info", `Student password: ${res.studentAccount.temporaryPassword}`);
              if (res.parentAccount?.temporaryPassword) toast("info", `Parent password: ${res.parentAccount.temporaryPassword}`);
              setOpen(false);
              void list.reload();
            } catch (e) {
              toast("err", e instanceof Error ? e.message : "Enrol failed");
            }
          }}
        >
          <Field label="First name"><input value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} required /></Field>
          <Field label="Last name"><input value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} required /></Field>
          <Field label="Class">
            <select value={form.classId} onChange={(e) => setForm({ ...form, classId: e.target.value, sectionId: "" })} required>
              <option value="">Select</option>
              {classes.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
            </select>
          </Field>
          <Field label="Section">
            <select value={form.sectionId} onChange={(e) => setForm({ ...form, sectionId: e.target.value })} required>
              <option value="">Select</option>
              {(sections[form.classId] || []).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
            </select>
          </Field>
          <Field label="Parent first name"><input value={form.parentFirstName} onChange={(e) => setForm({ ...form, parentFirstName: e.target.value })} /></Field>
          <Field label="Parent last name"><input value={form.parentLastName} onChange={(e) => setForm({ ...form, parentLastName: e.target.value })} /></Field>
          <Button type="submit" kind="brass">Save to database</Button>
        </Form>
      </Modal>
    </>
  );
}

export function UsersPage() {
  const [q, setQ] = useState("");
  const [role, setRole] = useState<Role | "">("");
  const list = useAsync(() => userApi.list({ q: q || undefined, role: role || undefined }), [q, role]);
  const [open, setOpen] = useState(false);
  const toast = useToast();
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", role: "TEACHER" as Role });
  const [temp, setTemp] = useState<string | null>(null);
  return (
    <>
      <div className="page-title">
        <div><h1>Users</h1><p>Usernames and temporary passwords are generated by the backend</p></div>
        <Button kind="brass" onClick={() => setOpen(true)}>Create user</Button>
      </div>
      {temp ? <div className="notice">Share once: <span className="pwd">{temp}</span></div> : null}
      <div className="row" style={{ marginBottom: 12 }}>
        <Search value={q} onChange={setQ} placeholder="Search users" />
        <select className="search" value={role} onChange={(e) => setRole(e.target.value as Role | "")}>
          <option value="">All roles</option>
          {["SCHOOL_ADMIN", "PRINCIPAL", "TEACHER", "ACCOUNT_OFFICER", "PARENT", "STUDENT"].map((r) => <option key={r}>{r}</option>)}
        </select>
      </div>
      {list.loading ? <Loading /> : list.error ? <ErrorBox error={list.error} /> : (
        <Table
          headers={["Name", "Username", "Role", "Status", ""]}
          rows={(list.data?.content || []).map((u) => [
            u.fullName, u.username, pretty(u.role), <Badge key={u.id} value={u.status} />,
            <Button key={`r${u.id}`} kind="ghost" onClick={async () => {
              try {
                const r = await userApi.resetPassword(u.id);
                setTemp(`${r.user.username} / ${r.temporaryPassword}`);
                toast("ok", "Password reset");
              } catch (e) { toast("err", e instanceof Error ? e.message : "Reset failed"); }
            }}>Reset password</Button>,
          ])}
        />
      )}
      <Modal title="Create user" open={open} onClose={() => setOpen(false)}>
        <Form onSubmit={async () => {
          try {
            const r = await userApi.create(form);
            setTemp(`${r.user.username} / ${r.temporaryPassword}`);
            toast("ok", "User created");
            setOpen(false);
            void list.reload();
          } catch (e) { toast("err", e instanceof Error ? e.message : "Create failed"); }
        }}>
          <Field label="First name"><input value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} required /></Field>
          <Field label="Last name"><input value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} required /></Field>
          <Field label="Email"><input value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field>
          <Field label="Role">
            <select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as Role })}>
              {["TEACHER", "PRINCIPAL", "ACCOUNT_OFFICER", "SCHOOL_ADMIN", "PARENT"].map((r) => <option key={r}>{r}</option>)}
            </select>
          </Field>
          <Button type="submit" kind="brass">Create</Button>
        </Form>
      </Modal>
    </>
  );
}
